controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dual_stepper_base_controller:
      type: diff_drive_controller/DiffDriveController

dual_stepper_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.2312
    wheel_radius: 0.065

    base_frame_id: base_link

    use_stamped_vel: false
    cmd_vel_timeout: 0.5

    publish_rate: 50.0
